### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by denisobrienirl** [nospaceships/node-yara#12]
Hi Stephen,

I'm trying to get my head around this weird issue when installing 'node-yara' module. Searched the vast of the Internet only to find the comments about not having libyara installed which i believe i do. Here are the steps i took before getting - 'fatal error: yara.h: No such file or directory'.

```
sudo apt-get install yara
npm install yara
```

The output i'm getting:
```
> yara@2.1.3 install /home/user/Documents/Development/my-project/node_modules/yara
> node-gyp rebuild

make: Entering directory '/home/user/Documents/Development/my-project/node_modules/yara/build'
  CXX(target) Release/obj.target/yara/src/yara.o
In file included from ../src/yara.cc:13:0:
../src/yara.h:8:10: fatal error: yara.h: No such file or directory
 #include <yara.h>
          ^~~~~~~~
compilation terminated.
yara.target.mk:91: recipe for target 'Release/obj.target/yara/src/yara.o' failed
make: *** [Release/obj.target/yara/src/yara.o] Error 1
make: Leaving directory '/home/user/Documents/Development/my-project/node_modules/yara/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Documents/Development/my-project/node_modules/yara
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
OS details:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
Yara version:
```
yara --version
3.7.1
```
Any help is much appreciated!

**Comment by stephenwvickers** [comment]
Hi,

Can you please install `libyara-dev` and try again:

```
sudo apt-get install libyara-dev
```

Looks like this could be omitted from my documentation :(

Thanks

Steve

**Comment by denisobrienirl** [comment]
Thanking you, good sir! This worked like a charm!

```
> yara@2.1.3 install /home/user/Documents/Development/my-project/node_modules/yara
> node-gyp rebuild

make: Entering directory '/home/user/Documents/Development/my-project/node_modules/yara/build'
  CXX(target) Release/obj.target/yara/src/yara.o
  SOLINK_MODULE(target) Release/obj.target/yara.node
  COPY Release/yara.node
make: Leaving directory '/home/user/Documents/Development/my-project/node_modules/yara/build'

+ yara@2.1.3
added 2 packages from 10 contributors in 9.711s
```

**Comment by stephenwvickers** [comment]
No problem. I'll get the docs updated.

Let me know if you have any feedback.

Thanks

Steve

**Comment by denisobrienirl** [comment]
Sure thing. Will do!

Thanks!

**Comment by denisobrienirl** [comment]
Hi Steve,

Since you're going to be updating the documentation, there is a minor issue with the sample code given in README.md.

This part here:
```
if (error instanceof CompileRulesError) {
	console.error(error.message + ": " + JSON.stringify(error.errors))
} else {
	console.error(error.message)
}
```
I believe 'yara.' infront of CompileRulesError is missing.

```
if (error instanceof **yara.**CompileRulesError) {
	console.error(error.message + ": " + JSON.stringify(error.errors))
} else {
	console.error(error.message)
}
```
Cheers,
